-- Knowledge base ingestion schema
-- Safe to re-run.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = timezone('utc', now());
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS kb_sources (
    id             bigint generated by default as identity PRIMARY KEY,
    created_at     timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at     timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    source_type    text NOT NULL,
    title          text NOT NULL DEFAULT '',
    source_url     text,
    raw_text       text,
    storage_bucket text,
    storage_path   text,
    mime_type      text,
    checksum       text,
    status         text NOT NULL DEFAULT 'pending',
    enabled        boolean NOT NULL DEFAULT true,
    last_synced_at timestamptz,
    sync_error     text,
    metadata       jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT kb_sources_type_check CHECK (source_type IN ('pdf_upload', 'web_url')),
    CONSTRAINT kb_sources_status_check CHECK (status IN ('pending', 'ready', 'syncing', 'error', 'disabled'))
);

CREATE INDEX IF NOT EXISTS idx_kb_sources_type_status
    ON kb_sources (source_type, status);

DROP TRIGGER IF EXISTS set_kb_sources_updated_at ON kb_sources;
CREATE TRIGGER set_kb_sources_updated_at
BEFORE UPDATE ON kb_sources
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE kb_sources ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow kb sources all" ON kb_sources;
CREATE POLICY "Allow kb sources all"
    ON kb_sources FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


CREATE TABLE IF NOT EXISTS kb_documents (
    id             bigint generated by default as identity PRIMARY KEY,
    created_at     timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at     timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    source_id      bigint NOT NULL REFERENCES kb_sources(id) ON DELETE CASCADE,
    external_id    text NOT NULL,
    document_type  text NOT NULL DEFAULT 'generic',
    title          text NOT NULL DEFAULT '',
    body_text      text NOT NULL DEFAULT '',
    checksum       text,
    metadata       jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_kb_documents_source_external
    ON kb_documents (source_id, external_id);

CREATE INDEX IF NOT EXISTS idx_kb_documents_source
    ON kb_documents (source_id);

DROP TRIGGER IF EXISTS set_kb_documents_updated_at ON kb_documents;
CREATE TRIGGER set_kb_documents_updated_at
BEFORE UPDATE ON kb_documents
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE kb_documents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow kb documents all" ON kb_documents;
CREATE POLICY "Allow kb documents all"
    ON kb_documents FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


CREATE TABLE IF NOT EXISTS kb_chunks (
    id          bigint generated by default as identity PRIMARY KEY,
    created_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    source_id   bigint NOT NULL REFERENCES kb_sources(id) ON DELETE CASCADE,
    document_id bigint NOT NULL REFERENCES kb_documents(id) ON DELETE CASCADE,
    chunk_index integer NOT NULL,
    title       text NOT NULL DEFAULT '',
    content     text NOT NULL DEFAULT '',
    checksum    text,
    token_count integer NOT NULL DEFAULT 0,
    embedding   jsonb NOT NULL DEFAULT '[]'::jsonb,
    metadata    jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_kb_chunks_document_index
    ON kb_chunks (document_id, chunk_index);

CREATE INDEX IF NOT EXISTS idx_kb_chunks_source
    ON kb_chunks (source_id);

ALTER TABLE kb_chunks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow kb chunks all" ON kb_chunks;
CREATE POLICY "Allow kb chunks all"
    ON kb_chunks FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS kb_ingest_jobs (
    id          bigint generated by default as identity PRIMARY KEY,
    created_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    source_id   bigint REFERENCES kb_sources(id) ON DELETE CASCADE,
    source_type text NOT NULL DEFAULT 'generic',
    job_type    text NOT NULL DEFAULT 'ingest',
    status      text NOT NULL DEFAULT 'pending',
    payload     jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_text  text,
    started_at  timestamptz,
    finished_at timestamptz,
    attempts    integer NOT NULL DEFAULT 0,
    last_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT kb_ingest_jobs_status_check CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_kb_ingest_jobs_status_created
    ON kb_ingest_jobs (status, created_at);

CREATE INDEX IF NOT EXISTS idx_kb_ingest_jobs_source
    ON kb_ingest_jobs (source_id);

DROP TRIGGER IF EXISTS set_kb_ingest_jobs_updated_at ON kb_ingest_jobs;
CREATE TRIGGER set_kb_ingest_jobs_updated_at
BEFORE UPDATE ON kb_ingest_jobs
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE kb_ingest_jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow kb ingest jobs all" ON kb_ingest_jobs;
CREATE POLICY "Allow kb ingest jobs all"
    ON kb_ingest_jobs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


INSERT INTO storage.buckets (id, name, public)
VALUES ('kb-files', 'kb-files', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public read kb files" ON storage.objects;
CREATE POLICY "Public read kb files"
    ON storage.objects
    FOR SELECT
    USING (bucket_id = 'kb-files');

DROP POLICY IF EXISTS "Allow kb files upload" ON storage.objects;
CREATE POLICY "Allow kb files upload"
    ON storage.objects
    FOR INSERT TO anon, authenticated
    WITH CHECK (bucket_id = 'kb-files');
