-- Supabase base setup for the backend-only Gemini branch.
-- Run first on a fresh project.

CREATE TABLE IF NOT EXISTS call_logs (
    id               bigint generated by default as identity primary key,
    created_at       timestamptz default timezone('utc', now()) not null,
    phone_number     text,
    caller_name      text,
    duration_seconds integer,
    transcript       text,
    summary          text,
    recording_url    text
);

ALTER TABLE call_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all actions for service role" ON call_logs;
CREATE POLICY "Enable all actions for service role"
    ON call_logs
    FOR ALL
    USING (true)
    WITH CHECK (true);

INSERT INTO storage.buckets (id, name, public)
VALUES ('call-recordings', 'call-recordings', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public read recordings" ON storage.objects;
CREATE POLICY "Public read recordings"
    ON storage.objects
    FOR SELECT
    USING (bucket_id = 'call-recordings');

DROP POLICY IF EXISTS "Service role write recordings" ON storage.objects;
CREATE POLICY "Service role write recordings"
    ON storage.objects
    FOR INSERT
    WITH CHECK (bucket_id = 'call-recordings');
